<?php
return [
    'hero_title'           => 'Comprometidos con el bienestar, la calidad y el desarrollo social.',
    'hero_subtitle'        => 'Transformando vidas, construyendo esperanzas',
    'hero_btn_primary'     => 'Solicitar información',
    'hero_btn_secondary'   => 'Conoce nuestros servicios',
    'hero_bg_image'        => 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1920&q=80',
    'about_title'          => '¿Quiénes somos?',
    'about_subtitle'       => 'Construimos bienestar a través de servicios integrales.',
    'about_content_1'      => '',
    'about_content_2'      => '',
    'about_img_url'        => 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80',
    'commitment_title'     => 'Nuestro compromiso',
    'commitment_subtitle'  => 'Más que prestar un servicio, construimos bienestar.',
    'commitment_content'   => '',
    'mission_title'        => 'Nuestra Misión',
    'mission_content'      => '',
    'vision_title'         => 'Nuestra Visión',
    'vision_content'       => '',
    'together_title'       => '¿Trabajemos juntos?',
    'together_content'     => 'Estamos preparados para desarrollar soluciones integrales.',
    'together_btn'         => 'Solicitar una propuesta',
    'footer_address'       => 'Ibagué – Tolima',
    'footer_email'         => '',
    'footer_phone'         => '',
    'footer_facebook'      => 'https://facebook.com',
    'footer_instagram'     => 'https://instagram.com',
    'footer_twitter'       => 'https://twitter.com',
    'footer_linkedin'      => 'https://linkedin.com',
    'theme_color_primary'  => '#9b98d5',
    'theme_color_secondary'=> '#86d2f1',
    'theme_color_dark'     => '#1e293b',
    'logo_path'            => 'logo1.png',
    'hero_logo_path'       => 'logo1.png',
    'contact_logo_path'    => 'logo1.png',
    'footer_logo_path'     => 'logo1.png',
    'logo_size'            => '72',
    'logo_offset_x'        => '0',
    'logo_offset_y'        => '0',
    'testimonials_enabled' => '1',
];
